/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Config.database;
import Controllers.*;
import Models.*;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TyZoX
 */
public class GerantReservation extends javax.swing.JFrame {

    /**
     * Creates new form GerantReservation
     */
    private final Connection conn;
     PreparedStatement preparedStmt;
     ResultSet rs;
    ClientController cc = new ClientController();
    ReservationController rc = new ReservationController();
    StatusController sc = new StatusController();
    Client c;
     
    public GerantReservation() {
        initComponents();
        this.listerClients();
        this.initListReservations();
        this.conn = database.getConnection();
         this.preparedStmt = null;
         this.rs = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableClients = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableReservations = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmdAccepter = new javax.swing.JButton();
        cmdRefuser = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelClose2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelMin2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClients);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Clients :");

        tableReservations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReservationsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableReservations);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Reservations :");

        cmdAccepter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdAccepter.setText("Accepté");
        cmdAccepter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdAccepter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAccepterActionPerformed(evt);
            }
        });

        cmdRefuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdRefuser.setText("Refusé");
        cmdRefuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdRefuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRefuserActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(59, 89, 152));

        jLabelClose2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose2.setText("X");
        jLabelClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose2MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gérant");

        jLabelMin2.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabelMin2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin2.setText("-");
        jLabelMin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMin2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/left-arrow (1).png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201)
                .addComponent(jLabelMin2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose2)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelClose2)
                        .addComponent(jLabelMin2)))
                .addGap(9, 9, 9))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imprimer.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdAccepter, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdRefuser, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdAccepter)
                        .addComponent(cmdRefuser)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientsMouseClicked
        // TODO add your handling code here:
        try{
            int SelectedRowIndex = tableClients.getSelectedRow();
            if(SelectedRowIndex == -1) return;
            int clientId = (int) tableClients.getValueAt(SelectedRowIndex, 0);
            c = cc.getById(clientId);
            listerReservations(c);
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_tableClientsMouseClicked

    private void tableReservationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReservationsMouseClicked

    }//GEN-LAST:event_tableReservationsMouseClicked

    private void cmdAccepterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAccepterActionPerformed
       
        int SelectedRowIndex = tableReservations.getSelectedRow();
        if(SelectedRowIndex == -1){
            JOptionPane.showMessageDialog(null, "Aucun reservation selectionner!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int resId = (int) tableReservations.getValueAt(SelectedRowIndex, 0);
          
        if(rc.getStatus(resId, 2)){
            JOptionPane.showMessageDialog(this, "La réservation est déjà acceptée");
            return ;
        }
        if(rc.getStatus(resId, 3)){
            JOptionPane.showMessageDialog(this, "La réservation est déjà refusée");
            return ;
        }
        
        if(rc.Accept(resId) > 0){
            JOptionPane.showMessageDialog(this, "La réservation acceptée");
            listerReservations(c);
               try {
            
            rc.sendAccept(resId);
        } catch (SQLException ex) {
            System.out.println("errur acceptte  email");
        } 
        }else{
            JOptionPane.showMessageDialog(null, "Echec!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
          
        
    }//GEN-LAST:event_cmdAccepterActionPerformed

    private void cmdRefuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRefuserActionPerformed

        int SelectedRowIndex = tableReservations.getSelectedRow();
        if(SelectedRowIndex == -1){
            JOptionPane.showMessageDialog(null, "Aucun reservation selectionner!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int resId = (int) tableReservations.getValueAt(SelectedRowIndex, 0);
        if(rc.getStatus(resId, 3)){
            JOptionPane.showMessageDialog(this, "La réservation est déjà refusée");
            return ;
        }
        // En Attente = 1
        // Accepter = 2
        // Refuser = 3
        if(rc.Refuse(resId) > 0){
            JOptionPane.showMessageDialog(this, "La réservation refusé");
            listerReservations(c);
             try {
            
            rc.sendRefuse(resId);
        } catch (SQLException ex) {
            Logger.getLogger(GerantReservation.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }else{
            JOptionPane.showMessageDialog(null, "Echec!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_cmdRefuserActionPerformed

    private void jLabelClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose2MouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabelClose2MouseClicked

    private void jLabelMin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMin2MouseClicked

         this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMin2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.hide();
        ClientLogin cl = new ClientLogin();
        cl.show();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
          Document doc = new Document();
        try {
            
            preparedStmt =conn.prepareStatement("SELECT reservations.Id,dateArrive,dateDepart,NbrPersonne,NbrNuit,Type,Name,NbrNuit*Tarif as \"Totale\" , status.Description FROM reservations,chambres,clients, status WHERE reservations.chambreTypeId=chambres.Id and reservations.clientId=clients.Id AND reservations.status=status.Id order by reservations.Id asc");
             rs=preparedStmt.executeQuery();
            
              try {
                  PdfWriter.getInstance(doc, new FileOutputStream("C:\\Users\\Youssef\\Downloads\\gestionhotelier\\JavaApplication1\\src\\imprimerPDF\\chambres.pdf"));
                    doc.open();
                 doc.add(new Paragraph("Bienvenue Chez Hôtel Maroc:                                                                    "+new Date().toLocaleString()));
                doc.add(new Paragraph("-----------------------------------------------------------------------------------------------------------------------------"));
                
                
                  
                try {
                  Image   img = Image.getInstance("C:\\Users\\Youssef\\Downloads\\gestionhotelier\\JavaApplication1\\src\\imprimerPDF\\img.jpg");
                  doc.add(img);
                  
                  doc.add(new Paragraph("-----------------------------------------------------------------------------------------------------------------------------"));
                  doc.add(new Paragraph("                                                                                                                             "));
                  doc.add(new Paragraph("                                                                                                                             "));
                  
                  doc.add(new Paragraph("                                       La Liste de Réservation des Chambres: "                                                ));
                  doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                 // doc.add(new Paragraph("                                                                                                                             "));
                  
                    
                     PdfPTable t = new PdfPTable(9);
                     t.setWidthPercentage(100);
                     PdfPCell cell;
                   cell=new PdfPCell(new Phrase("ID",FontFactory.getFont("Comic Sans MS ",10)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   cell.setBackgroundColor(BaseColor.GRAY);
                   t.addCell(cell);
                   
                   cell=new PdfPCell(new Phrase("Date Arrive",FontFactory.getFont("Comic Sans MS ",9)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   cell.setBackgroundColor(BaseColor.GRAY);
                   t.addCell(cell);
                   
                  
                   
                  cell=new PdfPCell(new Phrase("Date Depart",FontFactory.getFont("Comic Sans MS",9)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   cell.setBackgroundColor(BaseColor.GRAY);
                   t.addCell(cell);
                   
                   cell=new PdfPCell(new Phrase("Nombre Perssone",FontFactory.getFont("Comic Sans MS",8)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   cell.setBackgroundColor(BaseColor.GRAY);
                   t.addCell(cell);
                   
                    cell=new PdfPCell(new Phrase("Nombre Nuit",FontFactory.getFont("Comic Sans MS",8)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   cell.setBackgroundColor(BaseColor.GRAY);
                   t.addCell(cell);
                   
                   
                    cell=new PdfPCell(new Phrase("Type Chmabre",FontFactory.getFont("Comic Sans MS",9)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   cell.setBackgroundColor(BaseColor.GRAY);
                   t.addCell(cell);
                   
                    cell=new PdfPCell(new Phrase("Nom",FontFactory.getFont("Comic Sans MS",9)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   cell.setBackgroundColor(BaseColor.GRAY);
                   t.addCell(cell);
                   
                    cell=new PdfPCell(new Phrase("Prix Totale",FontFactory.getFont("Comic Sans MS",9)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   cell.setBackgroundColor(BaseColor.GRAY);
                   t.addCell(cell);
                   
                    cell=new PdfPCell(new Phrase("Description",FontFactory.getFont("Comic Sans MS",8)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   cell.setBackgroundColor(BaseColor.GRAY);
                   t.addCell(cell);
                   ///////////////////////////////////////////////////////////////////////////////////////////////
                   
                       while(rs.next()){
                   
                   cell=new PdfPCell(new Phrase(rs.getString("id"),FontFactory.getFont("Comic Sans MS ",10)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   t.addCell(cell);
                   
                   cell=new PdfPCell(new Phrase(rs.getString("dateArrive"),FontFactory.getFont("Comic Sans MS",9)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   t.addCell(cell);
                   
                  cell=new PdfPCell(new Phrase(rs.getString("dateDepart"),FontFactory.getFont("Comic Sans MS",9)));
                  cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   t.addCell(cell);
                   
                   cell=new PdfPCell(new Phrase(rs.getString("NbrPersonne"),FontFactory.getFont("Comic Sans MS",9)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   t.addCell(cell);
                   
                   cell=new PdfPCell(new Phrase(rs.getString("NbrNuit"),FontFactory.getFont("Comic Sans MS",9)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   t.addCell(cell);
                   
                   cell=new PdfPCell(new Phrase(rs.getString("Type"),FontFactory.getFont("Comic Sans MS",7)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   t.addCell(cell);
                   
                   cell=new PdfPCell(new Phrase(rs.getString("Name"),FontFactory.getFont("Comic Sans MS",9)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   t.addCell(cell);
                   
                   cell=new PdfPCell(new Phrase(rs.getString("Totale")+" DH",FontFactory.getFont("Comic Sans MS",9)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                   t.addCell(cell);
                   
                   cell=new PdfPCell(new Phrase(rs.getString("Description"),FontFactory.getFont("Comic Sans MS",10)));
                   cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                
                   t.addCell(cell);
                  
                   }
                   doc.add(t);
                   
                     /////////////////////////////////////////////////////////////////
                    
                    doc.add(new Paragraph("                                      "));
                    doc.add(new Paragraph("                                       "));
                    doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                    doc.add(new Paragraph("MERCI DE VOTRE CONNFIANCE"));
                    doc.add(new Paragraph("EMAIL: hotelh418@gmail.com"));
                    doc.close();
                    Desktop.getDesktop().open(new File("C:\\Users\\Youssef\\Downloads\\gestionhotelier\\JavaApplication1\\src\\imprimerPDF\\chambres.pdf"));
                 ////////////////////////////////////////////////////////////////////////////////////////////// 
                } catch (BadElementException ex) {
                    System.out.println(ex.getMessage());
                } catch (IOException ex) {
                     System.out.println(ex.getMessage());
                }
                          
                   
              } catch (DocumentException ex) {
                   System.out.println("errur de lien de pdf");
              }
             
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        } catch (FileNotFoundException ex) {
              System.out.println(ex.getMessage());
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerantReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerantReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerantReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerantReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerantReservation().setVisible(true);
            }
        });
    }
    private void listerClients(){
        DefaultTableModel m = new DefaultTableModel();
        m.setColumnIdentifiers( new String[]{"ID","Name","Email","Group"});
        for(Client c : cc.getAll()){
            if(!cc.isAdmin(c.getGroupId()))
            m.addRow(new Object[]{c.getIdClient(),c.getName(),c.getEmail(),cc.isAdmin(c.getGroupId()) == false ? "User" : "Gérant"});
        }
        tableClients.setModel(m);
    }
    private void listerReservations(Client c){
        DefaultTableModel m = new DefaultTableModel();
        m.setColumnIdentifiers( new String[]{"ID","Date Depart","DateArrive","Nombre Personne","Nombre Nuit","Chambre Categorie","ClientName","Status"});
        for(Reservation r : rc.getByIdClient(c.getIdClient())){
            //if(rc.isOnHold(r.getIdRes()))
            m.addRow(new Object[]{r.getIdRes(),r.getDateDepart(),r.getDateArrive(),r.getNbPersonne(),r.getNbNuit(),r.getChambre().getTypeChambre(),r.getClient().getName(), sc.getById(r.getStatus())});
        }
        tableReservations.setModel(m);
    }
    private void initListReservations(){
        DefaultTableModel m = new DefaultTableModel();
        m.setColumnIdentifiers( new String[]{"ID","Date Depart","DateArrive","Nombre Personne","Nombre Nuit","Chambre Categorie","ClientName","Status"});
        tableReservations.setModel(m);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAccepter;
    private javax.swing.JButton cmdRefuser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose2;
    private javax.swing.JLabel jLabelMin2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableClients;
    private javax.swing.JTable tableReservations;
    // End of variables declaration//GEN-END:variables
}
